[package]
name = "blockchain_rust"
version = "0.1.0"
authors = ["Kieran Gookey <kgookey@gmail.com>"]
edition = "2018"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
crypto-hash = "0.3.4"
hex = "0.3.2"